name: Android

on:
  push:
    branches: [ "devel" ]
  pull_request:
    branches: [ "devel" ]
env:
  ANDROID_NDK_VERSION: '25.0.8775105'
  ANDROID_CMAKE_VERSION: '3.22.1'

jobs:
  build_linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        BUILD_TYPE: [Release]
    steps:
    - uses: actions/checkout@v3
    
    
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
         distribution: "zulu"
         java-version: 11

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Cache NDK
      id: ndk-cache
      uses: actions/cache@v2
      with:
        path: /usr/local/lib/android/sdk/ndk
        key: ${{ runner.os }}-NdkCache-${{ env.ANDROID_NDK_VERSION }}
    - name: Install Android SDK dependencies and configure
      run: |
        echo y | sdkmanager "ndk;${{ env.ANDROID_NDK_VERSION }}"
        echo y | sdkmanager "cmake;${{ env.ANDROID_CMAKE_VERSION }}"
        CMAKE_PATH=${ANDROID_SDK_ROOT}/cmake/${{ env.ANDROID_CMAKE_VERSION }}
        export PATH=${CMAKE_PATH}/bin:$PATH
        export NINJA_EXE=${CMAKE_PATH}/bin/ninja
        export ANDROID_NDK=${ANDROID_SDK_ROOT}/ndk/${{ env.ANDROID_NDK_VERSION }}
        export ANDROID_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake
